# Generated by Django 3.1.7 on 2021-03-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='posts/images/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
